{% set name = "opentype-sanitizer" %}
{% set version = "8.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentype-sanitizer-{{ version }}.tar.gz
  sha256: 0b01a71314b6545544d540aa657ddf9fb6967bff69c57c8b5803aafbd7bf221a

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cython
    - meson
  host:
    - pip
    - python
    - cython
    - setuptools-scm
    - libzlib
  run:
    - python

test:
  imports:
    - ots
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googlefonts/ots-python
  summary: Python wrapper for the OpenType Sanitizer
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
