{% set name = "opentype-sanitizer" %}
{% set version = "9.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentype-sanitizer-{{ version }}.tar.gz
  sha256: 4b89660e166a1fe057ab1c6b63038fc48ee73e768e80e1bf982abaf7b16fa064

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cython
    - meson
  host:
    - pip
    - python
    - cython
    - setuptools-scm
    - libzlib
  run:
    - python

test:
  imports:
    - ots
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googlefonts/ots-python
  summary: Python wrapper for the OpenType Sanitizer
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
