{% set name = "opentype-sanitizer" %}
{% set version = "9.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 93b51d01118a037f5d429a1c366d05dabad84c20db170ba2bb337361c02f65b4

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cython
    - meson
  host:
    - pip
    - python
    - cython
    - setuptools
    - setuptools-scm
    - libzlib
  run:
    - python

test:
  imports:
    - ots
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googlefonts/ots-python
  summary: Python wrapper for the OpenType Sanitizer
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
